const itemsOptions = [
  {"id":1,"name":"eget orci vehicula","isCompleted":false,"parentId":14},
  {"id":2,"name":"orci","isCompleted":true,"parentId":2},
  {"id":3,"name":"est congue","isCompleted":true,"parentId":22},
  {"id":4,"name":"vel dapibus","isCompleted":true,"parentId":0},
  {"id":5,"name":"tortor risus","isCompleted":false,"parentId":46},
  {"id":6,"name":"nam nulla integer","isCompleted":true,"parentId":49},
  {"id":7,"name":"ac enim in","isCompleted":false,"parentId":7},
  {"id":8,"name":"eget tincidunt","isCompleted":false,"parentId":2},
  {"id":9,"name":"tortor duis mattis","isCompleted":true,"parentId":10},
  {"id":10,"name":"placerat praesent","isCompleted":false,"parentId":34},
  {"id":11,"name":"iaculis congue","isCompleted":false,"parentId":46},
  {"id":12,"name":"vestibulum","isCompleted":false,"parentId":28},
  {"id":13,"name":"varius","isCompleted":true,"parentId":23},
  {"id":14,"name":"commodo","isCompleted":false,"parentId":32},
  {"id":15,"name":"in quis justo","isCompleted":false,"parentId":1},
  {"id":16,"name":"elementum ligula","isCompleted":false,"parentId":0},
  {"id":17,"name":"porttitor lorem","isCompleted":true,"parentId":50},
  {"id":18,"name":"a feugiat et","isCompleted":true,"parentId":27},
  {"id":19,"name":"faucibus orci","isCompleted":false,"parentId":16},
  {"id":20,"name":"ultrices","isCompleted":true,"parentId":26},
  {"id":21,"name":"dictumst etiam","isCompleted":false,"parentId":25},
  {"id":22,"name":"id","isCompleted":true,"parentId":33},
  {"id":23,"name":"amet","isCompleted":true,"parentId":44},
  {"id":24,"name":"pretium","isCompleted":true,"parentId":36},
  {"id":25,"name":"cras pellentesque volutpat","isCompleted":true,"parentId":15},
  {"id":26,"name":"at","isCompleted":true,"parentId":26},
  {"id":27,"name":"nunc","isCompleted":true,"parentId":1},
  {"id":28,"name":"morbi non lectus","isCompleted":true,"parentId":28},
  {"id":29,"name":"ut dolor morbi","isCompleted":true,"parentId":18},
  {"id":30,"name":"lectus","isCompleted":false,"parentId":8},
  {"id":31,"name":"cursus id","isCompleted":true,"parentId":48},
  {"id":32,"name":"justo pellentesque viverra","isCompleted":true,"parentId":4},
  {"id":33,"name":"eu orci","isCompleted":true,"parentId":33},
  {"id":34,"name":"et commodo","isCompleted":true,"parentId":24},
  {"id":35,"name":"suscipit a","isCompleted":true,"parentId":41},
  {"id":36,"name":"magnis dis","isCompleted":true,"parentId":16},
  {"id":37,"name":"dictumst","isCompleted":true,"parentId":41},
  {"id":38,"name":"aliquet massa","isCompleted":true,"parentId":36},
  {"id":39,"name":"in","isCompleted":false,"parentId":40},
  {"id":40,"name":"nulla justo","isCompleted":true,"parentId":12},
  {"id":41,"name":"eget","isCompleted":true,"parentId":17},
  {"id":42,"name":"ipsum integer","isCompleted":false,"parentId":3},
  {"id":43,"name":"nunc nisl duis","isCompleted":true,"parentId":9},
  {"id":44,"name":"nunc vestibulum","isCompleted":false,"parentId":49},
  {"id":45,"name":"velit donec diam","isCompleted":false,"parentId":35},
  {"id":46,"name":"nonummy","isCompleted":false,"parentId":15},
  {"id":47,"name":"sapien ut nunc","isCompleted":true,"parentId":1},
  {"id":48,"name":"felis donec semper","isCompleted":false,"parentId":47},
  {"id":49,"name":"pulvinar","isCompleted":false,"parentId":37},
  {"id":50,"name":"volutpat in","isCompleted":true,"parentId":0}
];

module.exports = { itemsOptions }
